name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-front-image:v1

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: carburant-frontend
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker
          docker tag my-front-image:v1 gcr.io/carburant-frontend/my-front-image:v1
      - name: Push Docker image to GCR
        run: docker push gcr.io/carburant-frontend/my-front-image:v1

      - name: Deploy to GCR
        run: |
          gcloud run deploy carburant-frontend --image gcr.io/carburant-frontend/my-front-image:v1 --platform managed --region europe-west1 --allow-unauthenticated --port 8080
